apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        platform.example.com/team: platform
    name: billing-api-production
    namespace: argocd
spec:
    destination:
        namespace: platform-billing-api-d5279830
        server: https://kubernetes.default.svc
    project: default
    source:
        path: clusters/us-east-1/teams/platform/billing-api/req-5553944fd5279830
        repoURL: https://github.com/mcmoney/billing-api
        targetRevision: main
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=false
